
GET http://localhost:3000/api/getActions
Content-Type: application/json

###

POST  http://localhost:3000/api/createAction
Content-Type: application/json

{
    "description" : "unauth req"
}

###

PUT http://localhost:3000/api/createAction
Content-Type: application/json

{
    "id" : "recCT8HcFuO5mf9aO",
    "fields" : {
        "description" : "test update",
        "completed" : true
    }
}

###

DELETE  http://localhost:3000/api/createAction
Content-Type: application/json

{
    "id" : "recCT8HcFuO5mf9aO"
}