import { getSession, useUser } from "@auth0/nextjs-auth0";
import Head from "next/head";
import { useContext, useEffect } from "react";
import Action from "../components/Action";
import ActionForm from "../components/ActionForm";
import Navbar from "../components/Navbar";
import { ActionsContext } from "../contexts/ActionsContext";
import { minifyRecords, table } from "./api/utils/Airtable";

export default function Home({ initialActions }) {
  const { actions, setActions } = useContext(ActionsContext);
  const { user, error, isLoading } = useUser();

  useEffect(() => {
    setActions(initialActions);
  }, []);

  return (
    <div>
      <Head>
        <title>NPI Action Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar user={user} />
      <main>
        {user && (
          <>
            <h1 className="text-2xl text-center mb-4">My Action List</h1>
            <ActionForm />
            <ul>
              {actions &&
                actions.map((action) => (
                  <Action key={action.id} action={action} />
                ))}
            </ul>
          </>
        )}
        {!user && <p>Login to see and update your Action Tracker</p>}
      </main>
    </div>
  );
}

export const getServerSideProps = async (ctx) => {
  const session = getSession(ctx.req, ctx.res);
  let actions = [];

  try {
    if (session?.user) {
      actions = await table
        .select({
          filterByFormula: `userId = '${session.user.sub}'`,
        })
        .firstPage();
    }

    return {
      props: {
        initialActions: minifyRecords(actions),
      },
    };
  } catch (error) {
    console.error(error);
    return {
      props: {
        err: "Could not fetch actions",
      },
    };
  }
};
